import { createdTableMatcher } from '../analysis/new-tables.ts';
import {
  alterTableCommands,
  columnConstraints,
  hasColumnConstraint,
  relationName,
  type AstNode,
} from '../ast.ts';
import { defineRule } from '../define-rule.ts';

export interface AddingRequiredFieldOptions {
  /** Skip tables created by this same migration. */
  allowOnNewTables: boolean;
}

/** Adding a NOT NULL column with a constant default stopped rewriting here. */
const DEFAULT_WITHOUT_REWRITE_SINCE = 11;

export const addingRequiredField = defineRule<AddingRequiredFieldOptions>({
  name: 'adding-required-field',
  meta: {
    description: 'Adding a NOT NULL column needs a default.',
    rationale:
      'ADD COLUMN … NOT NULL with no default fails outright on a non-empty table. Give it a ' +
      'default, or add the column nullable, backfill, and set NOT NULL afterwards.',
    defaultSeverity: 'error',
    defaultOptions: { allowOnNewTables: true },
  },
  create(context) {
    const isNewTable = createdTableMatcher(context.source);
    const version = context.settings.targetPostgresVersion;

    return {
      AlterTableStmt(node, path) {
        const relation = relationName(node.relation);
        if (context.options.allowOnNewTables && isNewTable(relation)) return;

        for (const command of alterTableCommands(node)) {
          if (command['subtype'] !== 'AT_AddColumn') continue;

          const columnDef = (command['def'] as AstNode)?.['ColumnDef'];
          if (!columnDef) continue;
          // NOT NULL arrives as a constraint entry, not the `is_not_null` flag,
          // which libpg_query only sets for certain internal rewrites.
          if (!hasColumnConstraint(columnDef, 'CONSTR_NOTNULL') && !columnDef['is_not_null']) {
            continue;
          }

          const column = String(columnDef['colname'] ?? 'the new column');
          const hasDefault = hasColumnConstraint(columnDef, 'CONSTR_DEFAULT');
          const isGenerated = columnConstraints(columnDef).some((constraint) =>
            ['CONSTR_IDENTITY', 'CONSTR_GENERATED'].includes(String(constraint['contype'] ?? '')),
          );

          if (isGenerated) continue;

          if (!hasDefault) {
            context.report({
              statement: path.statement,
              message: `Adding NOT NULL column ${column} with no default fails outright on a non-empty table.`,
              help: `Give it a default, or add it nullable, backfill, then SET NOT NULL.`,
            });
            continue;
          }

          if (version < DEFAULT_WITHOUT_REWRITE_SINCE) {
            context.report({
              statement: path.statement,
              message: `On Postgres ${version}, adding NOT NULL column ${column} with a default rewrites the whole table under ACCESS EXCLUSIVE.`,
              help: `Add it nullable, backfill in batches, then SET NOT NULL.`,
            });
          }
        }
      },
    };
  },
  tests: {
    valid: [
      'ALTER TABLE t ADD COLUMN c int;',
      'ALTER TABLE t ADD COLUMN c int NOT NULL DEFAULT 0;',
      "ALTER TABLE t ADD COLUMN c text NOT NULL DEFAULT '';",
      {
        name: 'NOT NULL columns in CREATE TABLE are fine — the table is empty',
        sql: 'CREATE TABLE t (c int NOT NULL);',
      },
      {
        name: 'a table created in the same migration',
        sql: 'CREATE TABLE t (a int);\nALTER TABLE t ADD COLUMN c int NOT NULL;',
      },
      {
        name: 'a generated identity column supplies its own values',
        sql: 'ALTER TABLE t ADD COLUMN c int NOT NULL GENERATED BY DEFAULT AS IDENTITY;',
      },
      {
        name: 'a default is enough on Postgres 11 and later',
        sql: 'ALTER TABLE t ADD COLUMN c int NOT NULL DEFAULT 0;',
        settings: { targetPostgresVersion: 16 },
      },
    ],
    invalid: [
      {
        name: 'NOT NULL with no default fails on a non-empty table',
        sql: 'ALTER TABLE t ADD COLUMN c int NOT NULL;',
        errors: [
          { line: 1, column: 1, message: 'Adding NOT NULL column c with no default fails outright' },
        ],
      },
      {
        name: 'points at the three-step replacement',
        sql: 'ALTER TABLE t ADD COLUMN c int NOT NULL;',
        errors: [{ help: 'add it nullable, backfill, then SET NOT NULL' }],
      },
      {
        name: 'before Postgres 11 even a constant default rewrites the table',
        sql: 'ALTER TABLE t ADD COLUMN c int NOT NULL DEFAULT 0;',
        settings: { targetPostgresVersion: 10 },
        errors: [{ message: 'On Postgres 10, adding NOT NULL column c with a default rewrites' }],
      },
      {
        name: 'each column in a list is reported',
        sql: 'ALTER TABLE t ADD COLUMN a int NOT NULL, ADD COLUMN b int NOT NULL;',
        errors: 2,
      },
    ],
  },
});
