import { alterTableCommands, columnConstraints, relationName, typeNameOf, type AstNode } from '../ast.ts';
import { defineRule } from '../define-rule.ts';

const SERIAL_TYPES = new Set([
  'serial',
  'serial2',
  'serial4',
  'serial8',
  'smallserial',
  'bigserial',
]);

export const addingSerialPrimaryKeyField = defineRule<void>({
  name: 'adding-serial-primary-key-field',
  meta: {
    description: 'Do not add a serial primary key column to an existing table.',
    rationale:
      'It combines three expensive things at once: a column rewrite to fill the sequence, a ' +
      'unique index build, and an ACCESS EXCLUSIVE lock held across both.',
    help: 'Create a new table with the key instead, or backfill an identity column in steps.',
    defaultSeverity: 'error',
    defaultOptions: undefined,
  },
  create(context) {
    return {
      AlterTableStmt(node, path) {
        const relation = relationName(node.relation);

        for (const command of alterTableCommands(node)) {
          if (command['subtype'] !== 'AT_AddColumn') continue;

          const columnDef = (command['def'] as AstNode)?.['ColumnDef'];
          if (!columnDef) continue;
          if (!SERIAL_TYPES.has(typeNameOf(columnDef['typeName']))) continue;
          if (
            !columnConstraints(columnDef).some(
              (constraint) => constraint['contype'] === 'CONSTR_PRIMARY',
            )
          ) {
            continue;
          }

          context.report({
            statement: path.statement,
            message: `Adding serial primary key ${relation.qualified}.${columnDef['colname']} rewrites the table and builds a unique index, all under ACCESS EXCLUSIVE.`,
          });
        }
      },
    };
  },
  tests: {
    valid: [
      {
        name: 'a serial column that is not a primary key',
        sql: 'ALTER TABLE t ADD COLUMN counter serial;',
      },
      {
        name: 'an identity primary key',
        sql: 'ALTER TABLE t ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;',
      },
      {
        name: 'a serial primary key in CREATE TABLE rewrites nothing',
        sql: 'CREATE TABLE t (id serial PRIMARY KEY);',
      },
      'ALTER TABLE t ADD COLUMN c int;',
    ],
    invalid: [
      {
        sql: 'ALTER TABLE public.t ADD COLUMN id serial PRIMARY KEY;',
        errors: [
          { line: 1, column: 1, message: 'Adding serial primary key public.t.id rewrites the table' },
        ],
      },
      {
        name: 'bigserial is the same hazard',
        sql: 'ALTER TABLE t ADD COLUMN id bigserial PRIMARY KEY;',
        errors: 1,
      },
      {
        name: 'names all three costs',
        sql: 'ALTER TABLE t ADD COLUMN id serial PRIMARY KEY;',
        errors: [{ message: 'builds a unique index, all under ACCESS EXCLUSIVE' }],
      },
    ],
  },
});
