import {
  alterTableCommands,
  columnConstraints,
  describeType,
  relationName,
  stringList,
  tableElements,
  typeNameOf,
  type AstNode,
} from '../ast.ts';
import { defineRule } from '../define-rule.ts';
import type { Statement } from '../types.ts';

export interface PreferIdentityOptions {
  /** Permit `serial` / `bigserial` primary keys. */
  allowSerial: boolean;
  /** Permit `uuid` primary keys. */
  allowUuid: boolean;
  /**
   * When non-empty, a `uuid` primary key must default to one of these
   * functions, e.g. `['uuid_generate_v7']`. Empty accepts any default.
   */
  requiredUuidDefaults: string[];
}

const SERIAL_TYPES = new Set(['serial', 'serial2', 'serial4', 'serial8', 'smallserial', 'bigserial']);
const INTEGER_TYPES = new Set(['int2', 'int4', 'int8']);

export const preferIdentity = defineRule<PreferIdentityOptions>({
  name: 'prefer-identity',
  meta: {
    description: 'Primary keys use GENERATED … AS IDENTITY, not serial.',
    rationale:
      'A serial column is really an integer plus a separate sequence with its own ownership and ' +
      'permissions, which drift apart. Identity columns are the standard replacement and keep ' +
      'the sequence bound to the column.',
    defaultSeverity: 'error',
    defaultOptions: { allowSerial: false, allowUuid: true, requiredUuidDefaults: [] },
  },
  create(context) {
    const { options } = context;

    const inspect = (column: AstNode, table: string, statement: Statement): void => {
      const type = typeNameOf(column['typeName']);
      const constraints = columnConstraints(column);
      const name = String(column['colname'] ?? 'this column');
      const where = `${table}.${name}`;

      if (SERIAL_TYPES.has(type)) {
        if (options.allowSerial) return;
        context.report({
          statement,
          message: `Primary key ${where} uses ${type}, which leaves the sequence unbound to the column.`,
          help: 'Declare it GENERATED BY DEFAULT AS IDENTITY.',
        });
        return;
      }

      if (type === 'uuid') {
        if (!options.allowUuid) {
          context.report({
            statement,
            message: `Primary key ${where} is a uuid, which this project does not allow.`,
            help: 'Use an integer key declared GENERATED BY DEFAULT AS IDENTITY.',
          });
          return;
        }
        if (options.requiredUuidDefaults.length === 0) return;

        const generator = defaultFunctionName(constraints);
        if (generator && options.requiredUuidDefaults.includes(generator)) return;

        context.report({
          statement,
          message:
            `Primary key ${where} ` +
            `${generator ? `defaults to ${generator}()` : 'has no default'}.`,
          help:
            `Default it to one of ` +
            `${options.requiredUuidDefaults.map((fn) => `${fn}()`).join(', ')}.`,
        });
        return;
      }

      if (!INTEGER_TYPES.has(type)) return;
      if (constraints.some((constraint) => constraint['contype'] === 'CONSTR_IDENTITY')) return;

      context.report({
        statement,
        message: `Primary key ${where} is a plain ${describeType(column['typeName'])}.`,
        help: 'Declare it GENERATED BY DEFAULT AS IDENTITY.',
      });
    };

    return {
      CreateStmt(node, path) {
        const table = relationName(node.relation).qualified;
        const { columns, constraints } = tableElements(node);

        const keyed = new Set<string>();
        for (const constraint of constraints) {
          if (constraint['contype'] !== 'CONSTR_PRIMARY') continue;
          for (const key of stringList(constraint['keys'])) keyed.add(key);
        }

        for (const column of columns) {
          const isPrimary =
            keyed.has(String(column['colname'] ?? '')) ||
            columnConstraints(column).some(
              (constraint) => constraint['contype'] === 'CONSTR_PRIMARY',
            );
          if (isPrimary) inspect(column, table, path.statement);
        }
      },

      AlterTableStmt(node, path) {
        const table = relationName(node.relation).qualified;

        for (const command of alterTableCommands(node)) {
          if (command['subtype'] !== 'AT_AddColumn') continue;
          const column = (command['def'] as AstNode)?.['ColumnDef'];
          if (!column) continue;
          const isPrimary = columnConstraints(column).some(
            (constraint) => constraint['contype'] === 'CONSTR_PRIMARY',
          );
          if (isPrimary) inspect(column, table, path.statement);
        }
      },
    };
  },
  tests: {
    valid: [
      'CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY);',
      'CREATE TABLE t (id bigint GENERATED ALWAYS AS IDENTITY PRIMARY KEY);',
      {
        name: 'a uuid key is allowed by default',
        sql: 'CREATE TABLE t (id uuid PRIMARY KEY);',
      },
      {
        name: 'a serial column that is not the primary key',
        sql: 'CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, counter serial);',
      },
      {
        name: 'a plain integer column that is not the primary key',
        sql: 'CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, other int);',
      },
      {
        name: 'a text primary key is outside this rule',
        sql: 'CREATE TABLE t (id text PRIMARY KEY);',
      },
      {
        name: 'serial when explicitly permitted',
        sql: 'CREATE TABLE t (id serial PRIMARY KEY);',
        options: { allowSerial: true },
      },
      {
        name: 'a uuid key with the required generator',
        sql: 'CREATE TABLE t (id uuid PRIMARY KEY DEFAULT uuid_generate_v7());',
        options: { requiredUuidDefaults: ['uuid_generate_v7'] },
      },
      {
        name: 'a table-level primary key over an identity column',
        sql: 'CREATE TABLE t (id bigint GENERATED BY DEFAULT AS IDENTITY, PRIMARY KEY (id));',
      },
    ],
    invalid: [
      {
        name: 'a serial primary key',
        sql: 'CREATE TABLE t (id serial PRIMARY KEY);',
        errors: [{ line: 1, column: 1, message: 'Primary key t.id uses serial' }],
      },
      {
        name: 'points at the identity replacement',
        sql: 'CREATE TABLE t (id bigserial PRIMARY KEY);',
        errors: [{ help: 'GENERATED BY DEFAULT AS IDENTITY' }],
      },
      {
        name: 'a plain integer primary key with no identity',
        sql: 'CREATE TABLE t (id bigint PRIMARY KEY);',
        errors: [{ message: 'Primary key t.id is a plain bigint' }],
      },
      {
        name: 'a table-level primary key over a serial column',
        sql: 'CREATE TABLE t (id serial, PRIMARY KEY (id));',
        errors: 1,
      },
      {
        name: 'a uuid key missing the required generator',
        sql: 'CREATE TABLE t (id uuid PRIMARY KEY DEFAULT gen_random_uuid());',
        options: { requiredUuidDefaults: ['uuid_generate_v7'] },
        errors: [{ message: 'defaults to gen_random_uuid()', help: 'Default it to one of uuid_generate_v7()' }],
      },
      {
        name: 'a uuid key with no default at all',
        sql: 'CREATE TABLE t (id uuid PRIMARY KEY);',
        options: { requiredUuidDefaults: ['uuid_generate_v7'] },
        errors: [{ message: 'has no default', help: 'Default it to one of uuid_generate_v7()' }],
      },
      {
        name: 'uuid keys can be banned outright',
        sql: 'CREATE TABLE t (id uuid PRIMARY KEY);',
        options: { allowUuid: false },
        errors: [{ message: 'is a uuid, which this project does not allow' }],
      },
      {
        name: 'a primary key added by ALTER TABLE',
        sql: 'ALTER TABLE t ADD COLUMN id serial PRIMARY KEY;',
        errors: 1,
      },
    ],
  },
});

/** The bare function name a column's DEFAULT calls, if it calls one. */
function defaultFunctionName(constraints: readonly AstNode[]): string | null {
  for (const constraint of constraints) {
    if (constraint['contype'] !== 'CONSTR_DEFAULT') continue;
    const funcCall = constraint['raw_expr']?.['FuncCall'];
    if (!funcCall) continue;
    const parts = stringList(funcCall['funcname']);
    if (parts.length > 0) return parts[parts.length - 1]!;
  }
  return null;
}
